# Generated by Django 4.1.6 on 2023-02-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_hp_is_iii_gabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_HP', models.CharField(max_length=7)),
                ('Serial_Number', models.CharField(max_length=14)),
                ('IMEI_1', models.BigIntegerField()),
                ('IMEI_2', models.BigIntegerField()),
                ('Nama_Penanggung_Jawab', models.CharField(max_length=29)),
                ('Nopek', models.CharField(max_length=18)),
                ('Pengguna_Jabatan', models.CharField(max_length=56)),
                ('Bagian', models.CharField(max_length=40)),
                ('Fungsi', models.CharField(max_length=38)),
                ('No_HP_IS', models.CharField(max_length=38)),
                ('Alokasi', models.CharField(max_length=12)),
                ('Keterangan', models.CharField(max_length=94)),
            ],
        ),
    ]
