# Generated by Django 4.1.6 on 2023-02-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Alokasi',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Bagian',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Fungsi',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='IMEI_1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='IMEI_2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Keterangan',
            field=models.CharField(max_length=94, null=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Nama_Penanggung_Jawab',
            field=models.CharField(max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='No_HP_IS',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Nopek',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Pengguna_Jabatan',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
