# Generated by Django 4.1.6 on 2023-02-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_data_hp_is_iii_gabungan_alokasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Alokasi',
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Bagian',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Fungsi',
            field=models.CharField(blank=True, max_length=38),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='IMEI_1',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='IMEI_2',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Keterangan',
            field=models.CharField(blank=True, max_length=94),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Nama_Penanggung_Jawab',
            field=models.CharField(blank=True, max_length=29),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='No_HP_IS',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Nopek',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='data_hp_is_iii_gabungan',
            name='Pengguna_Jabatan',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
